config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions'}
  namespace :admin do
    resources :users, except: :destroy
    resources :assessments
  end
  root 'pages#home'
  resources :questions
  resources :answers
  resources :categories
  resources :user_assessments
  resources :assessments_results
end

app/models/assessment.rb
class Assessment < ApplicationRecord
  has_many :questions
  has_and_belongs_to_many :users
  has_many :assessments_users
end

app/controllers/admin/assessments_controller.rb
class Admin::AssessmentsController < AdministrationController

  def index
    @assessments = Assessment.all
  end

  def show
    @assessment = Assessment.find(params[:id])
    @user_assessment = UserAssessment.new
  end

  def new
    @assessment = Assessment.new
  end

  def create
    @assessment = Assessment.new(assessment_params)

    if @assessment.save
      redirect_to admin_assessment_path(@assessment)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def find_assessment
  end

  def assessment_params
    params.require(:assessment).permit(:title, :description)
  end


end

app/views/admin/assessments/_form.html.slim
= simple_form_for @assessment, url: admin_assessments_path  do |f|
  = f.input :title
  = f.input :description 
  = f.button :submit

app/views/admin/assessments/index.html.slim
h1 hello test 

app/views/admin/assessments/new.html.slim
h1 Add Assessment 

= render 'form'

app/views/admin/assessments/show.html.slim
h1 =@assessment.title
h1 =@assessment.description


h1 = link_to "add new category", new_category_path
h1 = link_to "add new question", new_question_path



- @assessment.questions.each do |question|
  h2 = question.title
  h4 = question.category.title



= simple_form_for @user_assessment do |f|
  = f.input :user_id, collection: User.all.map{|u| [u.first_name, u.id]}
  = f.input :assessment_id, collection: Assessment.all
  = f.button :submit