config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions'}
  namespace :admin do
    resources :users, except: :destroy
    resources :assessments
  end
  root 'pages#home'
  resources :questions
  resources :answers
  resources :categories
  resources :user_assessments
  resources :assessments_results
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :assessments_result
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assessment.rb
class Assessment < ApplicationRecord
  has_many :questions
  has_and_belongs_to_many :users
  has_many :assessments_users
end

app/models/assessments_result.rb
class AssessmentsResult < ApplicationRecord
  belongs_to :user_assessment
  belongs_to :user
  has_many :answers
  accepts_nested_attributes_for :answers
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :assessment
  has_many :questions
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers
  belongs_to :category
  belongs_to :assessment 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :first_name, :last_name
  
end

app/models/user_assessment.rb
class UserAssessment < ApplicationRecord
  belongs_to :user
  belongs_to :assessment
  has_one :assessments_result

  def average_for_category(category)
    (Answer.where('user_assessment_id = ? AND category_id = ?', self.id, category.id).sum(:result) / Answer.where('user_assessment_id = ? AND category_id = ?', self.id, category.id).count).to_f rescue 0
  end



end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdministrationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update user_params
    redirect_to admin_users_path(@user.id)
  end
private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email)
  end
end

app/controllers/administration_controller.rb
class AdministrationController < ApplicationController

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def new
    @answer = Answer.new
  end

  def update
  end

  def edit
  end

  def create
    @answer = Answer.new(answer_params)
    if @answer.save
      redirect_to answer_path(@answer)
    else
      render 'new'
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:result, :question_id, :user_assessment_id, :category_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/assessment_results_controller.rb
class AssessmentsResultsController < ApplicationController

  def index
    @assessments_results = AssessmentsResults.all
  end

  def new
    @assessments_result = AssessmentsResult.new
  end

  def create
    @assessments_result = AssessmentsResult.new(assessments_result_params)
    if @assessments_result.save
      redirect_to user_assessment_path(@user_assessment)
    else
      render 'new'
    end
  end

  private

  def assessments_result_params
    params.require(:assessments_result).permit(:result, :user_id)
  end

end

app/controllers/assessments_results_controller.rb
class AssessmentsResultsController < ApplicationController

  def index
    # @assessments_results = AssessmentsResult.all
  end

  def new
    @assessments_result = AssessmentsResult.new
  end

  def update
  end

  def show
    @assessments_result = AssessmentsResult.find(params[:id])
  end

  def edit
  end

  def create
    @assessments_result = AssessmentsResult.new(assessments_result_params)
    if @assessments_result.save
      redirect_to user_assessment_path(@user_assessment)
    else
      render 'new'
    end
  end

  private

  def assessments_result_params
    params.require(:assessments_result).permit(:result, :user_id)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all.order("created_at DESC")
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to category_path(@category)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  
  def find_category
  end

  def category_params
    params.require(:category).permit(:title, :assessment_id)
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end 
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.all.order("created_at DESC")
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)

    if @question.save
      redirect_to admin_assessment_path(@question.assessment_id), notice: "successfully created new Question"
      # redirect_to @question, notice: "successfully created new Question"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def find_question
  end

  def question_params
    params.require(:question).permit(:title, :assessment_id, :category_id)
  end


end

app/controllers/user_assessments_controller.rb
class UserAssessmentsController < ApplicationController

  def index
  end

  def create
    @user_assessment = UserAssessment.new(user_assessment_params)
    if @user_assessment.save
      AssessmentsResult.create(user_assessment_id: @user_assessment.id, result: nil, user_id: @user_assessment.user_id)
      @user_assessment.assessment.questions.each do |question|
        Answer.create(result: nil, question_id: question.id, user_assessment_id: @user_assessment.id, assessments_result_id: @user_assessment.assessments_result.id, category_id: question.category_id)
      end
      redirect_to user_assessment_path(@user_assessment)
    else
      render 'new'
    end
  end

  def new
  end

  def update
    @user_assessment = UserAssessment.find(params[:id])
    Answer.where(user_assessment_id: @user_assessment.id).each do |ans|
      ids = []
      params[:assessments_result][:answers_attributes].each { |thing| ids << thing.second['result'] if thing.second['id'] == ans.id.to_s }
      ans.update_columns(result: ids.join(', ').to_i)
    end
    redirect_to assessments_result_path(@user_assessment.assessments_result)
  end

  def show
    @user_assessment = UserAssessment.find(params[:id])
    @questions = @user_assessment.assessment.questions
    @result = @user_assessment.assessments_result
  end

  private

  def user_assessment_params
    params.require(:user_assessment).permit(:assessment_id, :user_id, :question_id, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assessments_results_helper.rb
module AssessmentsResultsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"

    title == content_for?(:title) ? yield(:title) : "Untitled"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tag
    = csp_meta_tag
    link[rel="stylesheet" href="https://cdn.jsdelivr.net/npm/foundation-sites@6.5.0-rc.2/dist/css/foundation.min.css" integrity="sha256-iJQ8dZac/jUYHxiEnZJsyVpKcdq2sQvdA7t02QFmp30= sha384-SplqNBo/0ZlvSdwrP/riIPDozO5ck8+yIm++KVqyMAC53S6m3BaV+2OLpi7ULOOh sha512-ho6hK4sAWdCeqopNZWNy1d9Ok2hzfTLQLcGSr8ZlRzDzh6tNHkVoqSl6wgLsqls3yazwiG9H9dBCtSfPuiLRCQ==" crossorigin="anonymous"]
  body
    p.notice
      = notice
    p.alert
      = alert

    == yield

    = javascript_include_tag "application"
     script[src="https://cdn.jsdelivr.net/npm/foundation-sites@6.5.0-rc.2/dist/js/foundation.min.js" integrity="sha256-G6jsRyH1fxbsvFIXSCuwYmI1aIDYBa28xscrvmYjJy0= sha384-vtoG68NvPc9azmFJr447vvY8qgdyA4FdaJ5/bqvzIM4eAdZfO0iyRRF8l2AAscYI sha512-43seCcNrHA0BQgrtyajB9sp8yOdv5c8QdYvgjP7zJ7v+dmzAcxYDQ2gupb9aztsNWBq1COIp/3NHYkQs4l/dkg==" crossorigin="anonymous"]


/ ssessmentsResult.last.answers.map{ |g| [g.question]}.flatten.map{|u| [u.category_id]}.flatten.uniq.map{|cat| {cat => Question.where(category_id: cat) } }.flatten
/
/ AssessmentsResult.last.answers.map{|f| [f.category_id]}.map{|v| Answer.where(category_id: v)}

app/views/pages/home.html.slim
.container.background-image
  = image_tag "home.svg"
  .button-container
    = link_to 'Logout', destroy_user_session_path, class: 'button1'
    = link_to 'Add Assessment', new_admin_assessment_path, class: 'button3'
    = link_to 'Login', new_user_session_path, class: 'button6'

    